### PR TITLE
Refactor as a Quarto extension

### PR DESCRIPTION
**Pull request by mcanouil**
Hi,

this PR updates this template to use the Quarto extension mechanism (and fix few display issues).
It also adds a simple/short readme with the Quarto command needed to use this template.

### CODE REVIEW

**Comment by beatrizmilz** [comment]
Hi @mcanouil ! This is new to me (how to create a quarto extension!). Thank you for this PR! I made this repo while experimenting quarto presentations for the first time. 

One question:
When someone uses `format: rladies-revealjs`, is it easy to overwrite the options used in the template? For example, logo, footer, color, etc...
Because I think it is nice to be able to easily change that if anyone wants it :)

**Comment by mcanouil** [comment]
Yes, it's like Rmarkdown template. It only sets some default values.
For example, after installing the extension, I can use R-Ladies theme and overwrite the logo using R Lille logo.
image

**Comment by beatrizmilz** [comment]
This is awesome! Thank you for your contribution.

**Comment by beatrizmilz** [comment]
How can I acknowledge you for this?

**Comment by beatrizmilz** [comment]
I'm trying to install it but the following error is showing:

```
beatrizmilz@MacBook-Air-de-Beatriz ~ % quarto install extension beatrizmilz/quarto-rladies-theme
ERROR: Too many arguments: beatrizmilz/quarto-rladies-theme
```
Do you have any idea how to fix it?

**Comment by mcanouil** [comment]
You probably have to update Quarto.
Below I installed the extension using Quarto `1.0.28`.
image

**Comment by mcanouil** [comment]
> How can I acknowledge you for this?

However you want, but I am also fine with being acknowledge by being the author of the commits^^
image

You can add some information in the README[^1], e.g. acknowledgement, the fact that it is inspired from the Xaringan theme, etc. (i.e., things that are currently in the template).

[^1]:Btw, I noticed some weird phrasing of mine that need to be corrected^^
Also, maybe remove the `.Rproj` file (I did not see it because I asked VSCode to hide those).

**Comment by beatrizmilz** [comment]
Thanks! I updated Quarto and was able to install it :) 🎉 
But I'm getting a weird error..

When I tried to render the `template.qmd` file from this repo, it worked fine!
But, when I created a new file to try it out, I got the message `ERROR: Unable to read the extension 'rladies'.
Please ensure that you provided the correct id and that the extension is installed.` 

with this YAML header:
```
---
title: "Untitled"
format: rladies-revealjs
editor: visual
---
```


Were you able to use the extension in new files as well?

> I noticed some weird phrasing of mine that need to be corrected^^

Which one?



Btw, i'm  new to developing quarto extensions. Can you point me to references and places you used to study about this? Thank you!

**Comment by mcanouil** [comment]
The screenshot where I modified the logo was an independent directory.

Ref: https://quarto.org/docs/extensions/formats.html#format-templates

When you install a Quarto extension, it is installed locally under the directory you are working in.
So you have to install the extension everywhere you want it to work.

**Pull request merged**
